## Declarative Deployment

For this example you can use any Kubernetes installation you have access to.
See the link:../INSTALL.adoc[INSTALL] documentation for some options you have.

Let's now look, how we can get out https://github.com/k8spatterns/random-generator[random-generator] application from version 1 to version 2 with different update strategies.

First, install the application in version 1 by using the given deployment descriptor

[source, bash]
----
kubectl create -f deployment.yml
----

This will deploy 3 replicas of the `random-generator` and configures a `RollingUpdate` update strategy (which would be also the default).

In

* Rolling update with random-generator version 1 and 2



kubectl create -f rolling-update.yml


while true; do
  curl -s http://random-generator.$(minikube ip).nip.io/info | jq '.version,.id'
  echo ===========================
  sleep 1
done


kubectl set image deployment random-generator random-generator=k8spatterns/random-generator:2.0


kubectl rollout status deploy random-generator
