# Service account required for watching to resources
apiVersion: v1
kind: ServiceAccount
metadata:
  name: expose-controller
---
# Bind to an appropriate permission
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: expose-controller
subjects:
- kind: ServiceAccount
  name: expose-controller
roleRef:
  name: edit
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
---
# Example Deployment using a config map as input for a template
# which is processed from an init-container
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    project: k8spatterns
    pattern: Controller
  name: expose-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expose-controller
  template:
    metadata:
      labels:
        project: k8spatterns
        pattern: Controller
        app: expose-controller
    spec:
      serviceAccountName: expose-controller
      containers:
      - name: kubeapi-proxy
        image: k8spatterns/kubeapi-proxy
      - name: expose-controller
        image: k8spatterns/curl-jq
        command:
        - "sh"
        - "/expose-script/expose-controller.sh"
        volumeMounts:
        - mountPath: "/expose-script"
          name: expose-controller-script
      volumes:
      - name: expose-controller-script
        configMap:
          name: expose-controller-script
