== Daemon Service

In this example, we learn how to create a _Daemon Service_ for allowing to run infrastructure-focused Pods on specific nodes.

This example assumes a Kubernetes installation is available.
In this case, it's best played through with Minikube, as we need some support for PVs.
Check the link:../../INSTALL.adoc#minikube[INSTALL] documentation for installing Minikube.

This example used our `random-generator` application for periodically seeding `/dev/random` by writing 100000 random numbers every time to `/dev/random`.

This daemon service is a makeup example that should never be used for any application, as the generated random number is not entirely random.

NOTE: You could achieve a similar effect with a _Periodic Job_ and appropriate `nodeSelector`. However, a _Daemon Service_ is still safer for such a task, as it works without changes for nodes that will be added later.

Nevertheless, let's create a DaemonSet with

[source, bash]
----
kubectl apply -f https://k8spatterns.io/DaemonService/daemonset.yml
----

You can now check the generated pods with

[source, bash]
----
kubectl get pods
----

You see one Pod per node of your cluster.
For Minikube, it should be a single pod, and you can check the logs as usual.

=== More Information

* https://oreil.ly/_YRZc[Daemon Service Example]
* https://oreil.ly/62c3q[DaemonSet]
* https://oreil.ly/nTSbi[Perform a Rolling Update on a DaemonSet]
* https://oreil.ly/CnHin[DaemonSets and Jobs]
* https://oreil.ly/yYHft[Create Static Pods]
