== NetworkSegmentation

ifndef::skipInstall[]
We recommend using a Minikube installation for this example. Please refer to the link:../../INSTALL.adoc#minikube[installation instructions] for details.

Before running these examples, you need to set up Minikube with a Container Network Interface (CNI) plugin that supports NetworkPolicies, such as Calico. Follow these steps to start and configure Minikube with Calico:

[source, bash]
----
minikube start --cni=calico
----

To verify that the Calico CNI plugin has been installed, use

[source, bash]
----
kubectl get pods -n kube-system | grep calico
----
endif::skipInstall[]

=== Network Policies

First, create a deployment of the random generator application with the following manifest:

[source,bash]
----
kubectl apply -f https://k8spatterns.io/NetworkSegmentation/random-generator-deployment.yml
----

Deploy a curl container to test if the random generator service is reachable:

[source,bash]
----
kubectl run curl --image=curlimages/curl --restart=Never --command -- sleep infinity
----

Get the IP address of the random-generator pod:

[source,bash]
----
RANDOM_GENERATOR_POD_IP=$(kubectl get pod -l app=random-generator -o jsonpath='{.items[0].status.podIP}')
echo $RANDOM_GENERATOR_POD_IP
----

You should be able to reach the our random-generator app from within the cluster. The following command should give you the usual JSON response including a random number:

[source,bash]
----
kubectl exec curl -- curl -s $RANDOM_GENERATOR_POD_IP:8080
----

==== Deny All Policy

Next, let's create the NetworkPolicy for denying all incoming traffic by applying

[source,bash]
----
kubectl apply -f https://k8spatterns.io/NetworkSegmentation/deny-all-networkpolicy.yml
----

Let's now attempt to access the random generator service from the curl container

[source,bash]
----
kubectl exec curl -- curl -m 5 $RANDOM_GENERATOR_POD_IP:8080
----

The request should time out due to the deny-all policy.

==== Allow Ingress from Pods

Now let's reenable the access again to only the random-generator Deployment. 

For this, create a NetworkPolicy that label-matches our Deployment and allows access from all Pods that habe a label `random-client: "true"`:

[source,bash]
----
kubectl apply -f https://k8spatterns.io/NetworkSegmentation/allow-access-networkpolicy.yml
----

You still should not be able to access the Pod from our original `curl` Pod. Check it out by using again this command, that should return with a timeout:

[source,bash]
----
kubectl exec curl -- curl -m 5 $RANDOM_GENERATOR_POD_IP:8080
----

Now create another curl client, but this time with a label `random-client` that allows to pass the ingress NetworkPolicy

[source,bash]
----
kubectl run random-client --image=curlimages/curl --labels=random-client=true \
                         --restart=Never --command -- sleep infinity
----

Finally, Attempt to access the random generator service from the curl-access container:

[source,bash]
----
kubectl exec random-client -- curl -s $RANDOM_GENERATOR_POD_IP:8080
----

You should receive a random number as the output again, indicating successful access to the random-generator service.

==== Egress Policies

Let's continue our journey and restrict the egress access for our curl in the Pod `random-client` that we have created above.

For this, apply the following resource file that will only allows cluster-internal traffic, except for `api.chucknorris.io` (you might need to check the IP adresses in this resource file whether they are still pointing to `api.chucknorris.io`):

[source,bash]
----
kubectl apply -f https://k8spatterns.io/NetworkSegmentation/allow-internal-egress-only.yml
----

To verify, whether our egress policies work, let's try the following three curl:

[source,bash]
----
kubectl exec random-client -- curl -sn 5 $RANDOM_GENERATOR_POD_IP:8080
----

[source,bash]
----
kubectl exec random-client -- curl -sm 5 https://github.com
----

[source,bash]
----
kubectl exec random-client -- curl -sm 5 https://api.chucknorris.io | jq .
----

Can you guess which one goes through and which have a timeout after 5s ?

For many more example and real world use cases of NetworkPolicies checkout the https://github.com/ahmetb/kubernetes-network-policy-recipes[Kubernetes Network Policy Recipes], which is really a great resource for NetworkPolicy setups

== Authorization Policies
