# A Job resource
---
apiVersion: batch/v1
kind: Job
metadata:
  # Use a generated name so that this descriptor can be 
  # used multiple times with "kubectl create" without conflicts 
  # because of jobs having the same names
  generateName: random-generator-
  labels:
    app: random-generator
spec:
  # Job should run 5 Pods
  completions: 5
  # 3 Pods should run in parallel
  parallelism: 3
  # Remove pods after 5 minutes when they are done
  ttlSecondsAfterFinished: 300 
  template:
    metadata:
      name: random-generator
    spec:
      containers:
      - image: k8spatterns/random-generator:1.0
        name: random-generator
        command:
        - java
        # Class running batch job
        - RandomRunner
        # 1. Arg: File to store data (on a PV)
        - /tmp/logs/random.log
        # 2. How many iterations
        - "10000"
        volumeMounts:
        - mountPath: /tmp/logs
          name: log-volume
      restartPolicy: OnFailure
      volumes:
      - name: log-volume
        persistentVolumeClaim:
          claimName: random-generator-log
