apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: random-generator
spec:
  updatePolicy:
    updateMode: "Off"
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: random-generator
