== Health Probe

For this example we need a Kubernetes installation as described in link:../../INSTALL.adoc[INSTALLATION.adoc].

Here we are reusing our https://github.com/k8spatterns/random-generator[random-generator] which also includes support for health checks.

To apply a Deployment with liveness and readiness check enabled, use

[source, bash]
----
kubectl create -f https://k8spatterns.io/HealthProbe/deployment.yml
----

This deployment introduces an artificial pause of 20 seconds before the application becomes ready.
To monitor the readiness and liveness states you best open an extra terminal with running

[source, bash]
----
kubectl get pods -w
NAME                                READY   STATUS        RESTARTS   AGE
random-generator-5856b5f774-54h6b   0/1     Running       0          5s
random-generator-5856b5f774-54h6b   1/1     Running       0          38s
----

The example apps expose to endpoints with which you can switch the state of the readiness and liveness checks.
For simplicity reasons, we haven't installed a Service or Ingress (but of course, you are free to do so!)

Instead we are using a simple port-forwarding directly to the pod to trigger the toggles:

[source, bash]
----
# Port forward to Pod. "pod" is an alias to pick the full name of the pod (see INSTALL.adoc)
kubectl port-forward deployment/random-generator 8080:8080 &
----

Now you can switch on/off the readiness/liveness checks and see how the cluster manages your pods:

[source, bash]
----
# Check liveness probe by querying the actuator
curl -s http://localhost:8080/actuator/health | jq .

# Toggle liveness check to off
curl -s http://localhost:8080/toggle-live

# Check liveness probe again
curl -s http://localhost:8080/actuator/health | jq .

# Watch the pods and wait a bit. What happens after 2-3 mins ?
kubectl get pods -w

# Now switch readiness off
curl -s http://localhost:8080/toggle-ready

# Watch the pods for 1-2 mins
kubectl get pods -w

# Toggle readiness back on
curl -s http://localhost:8080/toggle-ready

# Watch the pods again ...
kubectl get pods -w
----

=== More Information

* https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/[Configuring Liveness and Readiness Probes]
* http://kubernetes.io/docs/user-guide/production-pods/[Working with Containers in Production]
* https://cloud.google.com/blog/products/gcp/kubernetes-best-practices-setting-up-health-checks-with-readiness-and-liveness-probes[Kubernetes best practices: Setting up health checks with readiness and liveness probes]
* https://github.com/kubernetes/community/blob/master/contributors/design-proposals/node/resource-qos.md[Resource Quality of Service]
* https://blog.risingstack.com/graceful-shutdown-node-js-kubernetes/[Graceful shutdown with Node.js and Kubernetes]
* https://ahmet.im/blog/advanced-kubernetes-health-checks/[Advanced Health Check Patterns in Kubernetes]
* https://mesosphere.github.io/marathon/docs/readiness-checks.html[Readiness Checks by Marathon]
* https://mesosphere.github.io/marathon/docs/health-checks.html[Health Checks and Task Termination]
