== Health Probe

For this example we need a Kubernetes installation as described in link:../../INSTALL.adoc[INSTALLATION.adoc].

Here we are reusing our https://github.com/k8spatterns/random-generator[random-generator] which also includes support for health checks.

To apply a Deployment with liveness and readiness check enabled, use

[source, bash]
----
kubectl create -f https://k8spatterns.io/HealthProbe/deployment.yml
----

This deployment introduces an artificial pause of 20 seconds before the application becomes ready.

[source, bash]
----
kubectl get pods -w
NAME                                READY   STATUS        RESTARTS   AGE
random-generator-5856b5f774-54h6b   0/1     Running       0          5s
random-generator-5856b5f774-54h6b   1/1     Running       0          38s
----

=== Liveness Probes

The example application exposes two endpoints with which you can switch the state of the readiness and liveness checks manually.
For simplicity reasons, we haven't installed a Service or Ingress (but of course, you are free to do so!)

Instead we are using a simple port-forwarding directly to the pod to trigger the toggles:

[source, bash]
----
kubectl port-forward deployment/random-generator 8080:8080 2>&1 &
----

Now you can switch on/off the readiness/liveness checks and see how the cluster manages your pods:

Check liveness probe by querying the actuator:

[source, bash]
----
curl -s http://localhost:8080/actuator/health | jq .
----

Toggle liveness check to off:

[source, bash]
----
curl -s http://localhost:8080/toggle-live
----

Check liveness probe again:

[source, bash]
----
curl -s http://localhost:8080/actuator/health | jq .
----

Watch the pods and wait a bit. What happens after 2-3 mins ?

[source, bash]
----
kubectl get pods -w
----

=== Readiness Probes

Let's check now the readiness probes. For this first flip the readiness state to `false`:

[source, bash]
----
curl -s http://localhost:8080/toggle-ready
----

Watch the pods for 1-2 mins:

[source, bash]
----
kubectl get pods -w
----

Toggle readiness back on:

[source, bash]
---- 
curl -s http://localhost:8080/toggle-ready
----

Watch the pods again:

[source, bash]
----
kubectl get pods -w
----

==== Startup Probe

In this example, we will introduce a startup probe to our application. Startup probes are useful when an application takes a significant amount of time to start and become ready. With a startup probe, you can give your application enough time to start and become ready without affecting the liveness and readiness probes.

To update the deployment with the startup probe enabled, use the following command:

[source, bash]
----
kubectl apply -f https://k8spatterns.io/HealthProbe/startup-deployment.yml
----

This deployment introduces an artificial startup delay of 60 seconds before the application becomes ready.
It configures are startup probe the kicks in after 20 seconds after container has been created and then checks every 10 seconds.

Using

[source, bash]
----
kubectl get pods -w
-----

you should see then an output that indicates that the Pod gets ready after roughly 60 seconds

----
NAME                                READY   STATUS        RESTARTS   AGE
random-generator-5856b5f774-54h6b   0/1     Running       0          5s
random-generator-5856b5f774-54h6b   1/1     Running       0          1m
----

=== Readiness Gates

Readiness gates provide an additional check that must be satisfied before a pod is considered ready. To demonstrate the usage of readiness gates, let's modify the existing deployment with a readiness gate includes:

[source, bash]
----
kubectl apply -f https://k8spatterns.io/HealthProbe/readiness-gate-deployment.yml
----

The custom readiness gate example.com/CustomReadiness is added to the pod spec. This readiness gate must be satisfied in addition to the existing readiness probe for the pod to be considered ready.

Checking with `kubectl get pods -w` shows, that the Pod doesn't get ready, since nobody add the condition `k8spatterns.io/read` with a value `True` to the Pod's status.

Let's do this now. We are using `kubectl` here, but usually this would be done with a controller which monitors the Pod and its dependencies.

First, find out the Pod's name and store it in a variables:

[source, bash]
----
pod=$(kubectl get pods -l app=random-generator -o name)
----

Then let's patch the Pod's status and add the readiness condition:

[source, bash]
----
kubectl patch $pod --type='json' \
  -p='[{"op": "add", \
        "path": "/status/conditions/-", \
        "value": {"type": "example.com/CustomReadiness", \
                  "status": "True", \
                  "reason": "CustomReadinessCheck", \
                  "message": "Custom readiness condition is satisfied", \
                  "lastProbeTime": null, \
                  "lastTransitionTime": null}}]'
----

Finally, let's check again if the Pod gets ready with the readiness gate fullfilled:

[source, bash]
----
kubect get pods -w
----

That concludes our demo for the _Health Probe_ pattern.
Don't forget to stop the two background processes when done with this example (executing twice `fg` followed by a `CTRL-C`)

=== More Information

* https://oreil.ly/moMx7[Health Probe Example]
* https://oreil.ly/h862g[Configure Liveness, Readiness, and Startup Probes]
* https://oreil.ly/q0wKy[Kubernetes Best Practices: Setting Up Health Checks with Readiness and Liveness Probes]
* https://oreil.ly/kEik7[Graceful Shutdown with Node.js and Kubernetes]
* https://oreil.ly/MHbup[Kubernetes Startup Probe—Practical Guide]
* https://oreil.ly/h_W1G[Improving Application Availability with Pod Readiness Gates]
* https://oreil.ly/O2sA2[Customizing the Termination Message]
* https://oreil.ly/lhetJ[SmallRye Health]
* https://oreil.ly/7kYX6[Spring Boot Actuator: Production-Ready Features]
* https://oreil.ly/aKEGe[Advanced Health Check Patterns in Kubernetes]
