# An indexed job that splits up a file
# Run this job after job.yaml
---
apiVersion: batch/v1
kind: Job
metadata:
  # Use a generated name so that this descriptor can be 
  # used multiple times with "kubectl create" without conflicts 
  # because of jobs having the same names
  generateName: file-split-
  labels:
    app: random-generator
spec:
  # Completion mode needs to be set to "Indexed"
  completionMode: Indexed
  # Job should run 5 Pods, all in parallel
  completions: 5
  parallelism: 5
  template:
    metadata:
      name: file-split
    spec:
      containers:
      - image: alpine
        name: split
        command:
        - "sh"
        - "-c"
        - |
          start=$(expr $JOB_COMPLETION_INDEX \* 10000)
          end=$(expr $JOB_COMPLETION_INDEX \* 10000 + 10000)
          awk "NR>=$start && NR<$end" /logs/random.log \
              > /logs/random-$JOB_COMPLETION_INDEX.txt
        volumeMounts:
        - mountPath: /logs
          name: log-volume
      # Retry again if failed (this field is mandatory)
      restartPolicy: Never
      volumes:
      - name: log-volume
        persistentVolumeClaim:
          # Same volume claim that is referenced in job.yaml
          claimName: random-generator-log
